version: "3.8"

services:
  server:
    container_name: resume_analyzer_server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
