export const CONSTANTS = {
  MAX_FILE_SIZE: 1024 * 1024 * 5,
  MAX_FILE_UPLOADS: 50,
  AWS_S3_BUCKET: "resume-analysis-01",
  ACCESS_TOKEN_EXPIRATION: "2m",
  REFRESH_TOKEN_EXPIRATION: "30d",
  COOKIE_EXPIRATION: "30d",
};
